servers:
  1:
          name: vultr-fc-web
          ip: 95.179.203.174
          port: "22"
          dbtype: MYSQL
          configs:
                    - /etc/apache2
                        - /etc/httpd
                            - /etc/httpd.conf
                                - /etc/mysql/my.cnf
                                    - /etc/nginx
                                        - /etc/varnish
                                            - /etc/redis
          databases:
                    - bukstk_db43
          db_excludes:
                  files:
                            - /home/bukstackdocumentatie-cyvhe/bukstackdocumentatie.flexicloud.in/BookStack
